services:
  - type: web
    name: shop-swift
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shop-swift-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src

databases:
  - name: shop-swift-db
    databaseName: shopswift
    plan: free