services:
  - type: web
    name: shop-swift
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd client && npm install && npm run build
    startCommand: |
      rm -rf client/node_modules/.cache
      gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: shop-swift-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: NODE_VERSION
        value: 16.0.0
    routes:
      - type: web
        path: /api
        spa: false
      - type: web
        path: /
        spa: true
        staticAssetsDirectory: client/build

databases:
  - name: shop-swift-db
    databaseName: shopswiftdb
    user: shopswift
    plan: free