services:
  - type: web
    name: plantsy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/plantsy
    healthCheckPath: /plants

  - type: web
    name: plantsy-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html