services:
  - type: web
    name: shop-swift
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shop-swift-db
          property: connectionString

databases:
  - name: shop-swift-db
    databaseName: shopswift
    plan: free